import sys
import os
import json

def extract_math(ocr_results):
    # In production, this would pass images to Pix2Text or Nougat.
    # For architecture proof, we perform a lightweight heuristic pass to identify math strings.
    math_results = []
    
    for result in ocr_results:
        text = result["text"]
        # Basic heuristic: contains typical math symbols or numbers mixed with variables
        if any(c in text for c in ["=", "+", "-", "/", "^", "\\", "{", "}", "_", "(", ")"]) and not text.isalpha():
            math_results.append({
                "region_id": result["region_id"],
                "math_text": text, # In prod, this would be LaTeX generated by Pix2Text
                "confidence": 0.95
            })
            
    return math_results

def main():
    if len(sys.argv) < 3:
        print("Usage: python stage4_math.py <pdf_path> <job_id>", file=sys.stderr)
        sys.exit(1)
        
    job_id = sys.argv[2]
    base_dir = os.path.join(os.getcwd(), "public", "uploads", "cbt_assets", job_id)
    ocr_path = os.path.join(base_dir, "ocr.json")
    
    if not os.path.exists(ocr_path):
        print("Error: ocr.json not found. Run Stage 3 first.", file=sys.stderr)
        sys.exit(1)
        
    with open(ocr_path, "r", encoding="utf-8") as f:
        ocr_data = json.load(f)
        
    math_data = {
        "job_id": job_id,
        "pages": []
    }
    
    for page_data in ocr_data["pages"]:
        page_num = page_data["page_num"]
        math_results = extract_math(page_data["ocr"])
        
        math_data["pages"].append({
            "page_num": page_num,
            "math": math_results
        })
        print(f"Extracted {len(math_results)} math equations on Page {page_num}")
        
    math_path = os.path.join(base_dir, "math.json")
    with open(math_path, "w", encoding="utf-8") as f:
        json.dump(math_data, f, indent=2)
        
    print(f"Math extraction complete. Saved to {math_path}")

if __name__ == "__main__":
    main()
