export const STORAGE_KEYS = {
  questionBank: "examgrid:question-bank",
  examCatalog: "examgrid:exam-catalog",
  students: "examgrid:students",
  batches: "examgrid:batches",
  schedules: "examgrid:exam-schedules",
  auditLogs: "examgrid:audit-logs",
  sessionMetrics: "examgrid:session-metrics",
  activeExamSessions: "examgrid:active-exam-sessions",
  adminSession: "examgrid:admin-session",
  workspaceSession: "examgrid:workspace-session",
  cbtTests: "examgrid:cbt-tests",
  cbtFinalAttempts: "examgrid:cbt-final-attempts",
  testSessions: "examgrid:test-sessions",
  platformInstitutes: "examgrid:platform-institutes",
} as const;
