import { getDefaultSolutionProvider, getDefaultVerifierProvider } from "@/intelligence/providers/provider-registry";
import { intelligenceId, nowIso } from "@/intelligence/lib/ids";
import { getIntelligenceRepository } from "@/intelligence/repositories/provider";
import type { VerificationRecord } from "@/intelligence/repositories/interfaces/intelligence-repository";
import {
  verificationResultSchema,
  type VerificationResult,
} from "@/intelligence/types/pipeline";

const VERIFY_SYSTEM = `You verify competitive exam solutions from another AI model.
Return ONLY valid JSON:
{
  "agreementScore": number between 0 and 1,
  "confidenceScore": number between 0 and 1,
  "status": "agreed" | "disputed" | "low_confidence",
  "discrepancies": string[],
  "reviewerNotes": string
}`;

export async function verifySolution(
  solutionId: string,
): Promise<VerificationRecord> {
  const repo = getIntelligenceRepository();
  const solution = repo.getSolution(solutionId);
  if (!solution) throw new Error(`Solution not found: ${solutionId}`);

  const question = repo.getStructuredQuestion(solution.structuredQuestionId);
  if (!question) {
    throw new Error(`Question not found: ${solution.structuredQuestionId}`);
  }

  const verifier = getDefaultVerifierProvider();
  const primary = getDefaultSolutionProvider();

  const payload = JSON.stringify({
    questionText: question.segment.questionText,
    options: question.segment.options,
    correctAnswer: question.segment.correctAnswer,
    primaryProviderId: solution.providerId,
    primarySolution: solution.structured,
  });

  const response = await verifier.complete({
    messages: [
      { role: "system", content: VERIFY_SYSTEM },
      {
        role: "user",
        content: `Verify this solution (generated by ${primary.displayName}):\n${payload}`,
      },
    ],
    responseFormat: "json",
    temperature: 0.1,
  });

  let result: VerificationResult;
  try {
    result = verificationResultSchema.parse(JSON.parse(response.content));
  } catch {
    result = {
      agreementScore: 0.5,
      confidenceScore: 0.4,
      status: "low_confidence",
      discrepancies: ["Failed to parse verifier JSON"],
      reviewerNotes: response.content.slice(0, 300),
    };
  }

  if (result.agreementScore < 0.6) result.status = "disputed";
  else if (result.confidenceScore < 0.55) result.status = "low_confidence";
  else if (result.status !== "disputed" && result.status !== "low_confidence") {
    result.status = "agreed";
  }

  const now = nowIso();
  const record: VerificationRecord = {
    id: intelligenceId("ver"),
    solutionId,
    structuredQuestionId: solution.structuredQuestionId,
    primaryProviderId: solution.providerId,
    verifierProviderId: verifier.id,
    result,
    rawVerifierResponse: response.content,
    createdAt: now,
    updatedAt: now,
  };

  repo.saveVerification(record);

  if (result.status === "low_confidence" || result.status === "disputed") {
    repo.updateSolution(solutionId, { reviewStatus: "needs_edit" });
  }

  return record;
}
